development:
  adapter: postgresql
  database: stock_portfolio_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: stock_portfolio_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: stock_portfolio_production
  pool: 5
  timeout: 5000
